### ISSUE TITLE
[BUG] Can't encode class java.lang.Long to json

### ISSUE THREAD

**Issue by markathomas** [vaadin/platform#1431]
**Describe the bug**

The Element API doesn't allow encoding of Long values to son though there's nothing technically preventing it in Javascript  AFAIK.

**To Reproduce**
1. Call Element.callJsFunction method with a long value as a parameter

**Expected behavior**
Longs are encoded to JSON

**Desktop (please complete the following information):**
 - Version 14
 - Vaadin platform version 14.2.3

**Additional context**
```
java.lang.IllegalArgumentException: Can't encode class java.lang.Long to json
	at com.vaadin.flow.internal.JsonCodec.encodeWithoutTypeInfo(JsonCodec.java:205)
	at com.vaadin.flow.internal.JsonCodec.encodeWithTypeInfo(JsonCodec.java:92)
	at com.vaadin.flow.component.internal.UIInternals$JavaScriptInvocation.<init>(UIInternals.java:124)
	at com.vaadin.flow.dom.Element.scheduleJavaScriptInvocation(Element.java:1734)
	at com.vaadin.flow.dom.Element.callJsFunction(Element.java:1638)
```

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible. ' first issue
