### ISSUE TITLE
Webpack Exited Prematurely

### ISSUE THREAD

**Issue by Horus360** [vaadin/platform#2642]
### Describe the bug

While setting up an Empty Project using Vaadin Start by Running Command "mvnw". Exception is thrown on the Webpage "`java.lang.IllegalStateException: Webpack exited prematurely`"

### Expected-behavior

Webpage Should be Loaded Successfully with "Hello World"

### Reproduction

- Go To [Vaadin Start](https://start.vaadin.com/app/) 
- Go To Settings Tab
- Under Settings Tab, Technology Section. Select Vaadin 22 or Vaadin 23(pre)
- Select Java 11
- Select Flow (Java Only)
- Select npm only
- Click on Download
- Unzip and run Command `mvnw`

### System Info

- OS - Windows 10
- JDK - 11
- NodeVersion - 16.13.1
- NPM Version - 7.13.0

**Comment by Artur-** [comment]
There is probably some more details in the server log

**Comment by Horus360** [comment]
Please find below Error Logs For Additional Info

```
------------------ Starting Frontend compilation. ------------------
2022-01-08 17:16:14.279  INFO 21148 --- [onPool-worker-3] c.v.b.devserver.AbstractDevServerRunner  : Running Webpack to compile frontend resources. This may take a moment, please stand by...
2022-01-08 17:16:19.097  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Project is running at:
2022-01-08 17:16:19.097  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Loopback: http://localhost:61490/
2022-01-08 17:16:19.097  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] On Your Network (IPv4): http://192.168.1.143:61490/
2022-01-08 17:16:19.097  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Content not from webpack is served from 'D:\my-app\target\classes\META-INF\VAADIN\webapp, D:\my-app\src\main\webapp' directory
2022-01-08 17:16:19.251  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : node:events:368
2022-01-08 17:16:19.251  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       throw er; // Unhandled 'error' event
2022-01-08 17:16:19.252  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       ^
2022-01-08 17:16:19.253  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
2022-01-08 17:16:19.254  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Error: spawn D:\my-app\node_modules\esbuild\esbuild.exe ENOENT
2022-01-08 17:16:19.254  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
2022-01-08 17:16:19.255  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at onErrorNT (node:internal/child_process:477:16)
2022-01-08 17:16:19.255  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-01-08 17:16:19.256  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Emitted 'error' event on ChildProcess instance at:
2022-01-08 17:16:19.256  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
2022-01-08 17:16:19.256  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at onErrorNT (node:internal/child_process:477:16)
2022-01-08 17:16:19.257  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2022-01-08 17:16:19.257  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   errno: -4058,
2022-01-08 17:16:19.257  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   code: 'ENOENT',
2022-01-08 17:16:19.257  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   syscall: 'spawn D:\\my-app\\node_modules\\esbuild\\esbuild.exe',
2022-01-08 17:16:19.258  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   path: 'D:\\my-app\\node_modules\\esbuild\\esbuild.exe',
2022-01-08 17:16:19.258  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   spawnargs: [ '--service=0.12.29', '--ping' ]
2022-01-08 17:16:19.258  INFO 21148 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : }
2022-01-08 17:16:19.445 ERROR 21148 --- [nio-8080-exec-4] c.v.flow.server.DefaultErrorHandler      :

java.lang.IllegalStateException: Webpack exited prematurely
        at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:220) ~[vaadin-dev-server-9.0.2.jar:na]
        at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:172) ~[vaadin-dev-server-9.0.2.jar:na]
        at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:163) ~[vaadin-dev-server-9.0.2.jar:na]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]

```

**Comment by Horus360** [comment]
**Workaround**
After encountering the above Error. Stop the Server and run a command manually and then restart using `mvnw`. I am able to start the application
`node ./node_modules/esbuild/install.js`

**Comment by magnusahlden** [comment]
I have very similar problem. After running into the problem no previous version (tested with 19, 21, 22) is starting. Even trying with my extensive fix-script (see https://gist.github.com/magnusahlden/213fbe12a9e2cd0e438f8b9105ae3147) I can get it to work...

the command 

> node ./node_modules/esbuild/install.js

 does nothing for me...

```

------------------ Starting Frontend compilation. ------------------
2022-01-24 13:52:19.086  INFO 83662 --- [nPool-worker-19] c.v.b.devserver.AbstractDevServerRunner  : Running Webpack to compile frontend resources. This may take a moment, please stand by...
2022-01-24 13:52:20.746  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : (node:83695) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
2022-01-24 13:52:20.746  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : (Use `node --trace-deprecation ...` to show where the warning was created)
2022-01-24 13:52:20.818  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Project is running at:
2022-01-24 13:52:20.818  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Loopback: http://localhost:61382/
2022-01-24 13:52:20.818  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] On Your Network (IPv4): http://192.168.100.253:61382/
2022-01-24 13:52:20.818  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:61382/
2022-01-24 13:52:20.818  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Content not from webpack is served from '/opt/xxx/admin-complex/target/classes/META-INF/VAADIN/webapp, /opt/xxx/admin-complex/src/main/webapp' directory
2022-01-24 13:52:23.135  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : (node:83695) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
2022-01-24 13:52:23.135  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
2022-01-24 13:52:23.135  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
2022-01-24 13:52:23.135  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
2022-01-24 13:52:23.419  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in ./xxx.css
2022-01-24 13:52:23.419  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Module build failed (from ../node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/cjs.js):
2022-01-24 13:52:23.419  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
2022-01-24 13:52:23.419  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  - options.url should be one of these:
2022-01-24 13:52:23.419  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    boolean | object { filter? }
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Allows to enables/disables `url()`/`image-set()` functions handling.
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Read more at https://github.com/webpack-contrib/css-loader#url
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    Details:
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be a boolean.
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be an object:
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       object { filter? }
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at validate (/opt/xxxx/admin-complex/node_modules/.pnpm/schema-utils@3.1.1/node_modules/schema-utils/dist/validate.js:105:11)
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.getOptions (/opt/xxxx/admin-complex/node_modules/.pnpm/webpack@5.67.0_webpack-cli@4.9.0/node_modules/webpack/lib/NormalModule.js:580:19)
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.loader (/opt/xxxx/admin-complex/node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/index.js:31:27)
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in ./commended-app-layout.css
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Module build failed (from ../node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/cjs.js):
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
2022-01-24 13:52:23.420  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  - options.url should be one of these:
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    boolean | object { filter? }
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Allows to enables/disables `url()`/`image-set()` functions handling.
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Read more at https://github.com/webpack-contrib/css-loader#url
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    Details:
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be a boolean.
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be an object:
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       object { filter? }
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at validate (/opt/xxxx/admin-complex/node_modules/.pnpm/schema-utils@3.1.1/node_modules/schema-utils/dist/validate.js:105:11)
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.getOptions (/opt/xxxx/admin-complex/node_modules/.pnpm/webpack@5.67.0_webpack-cli@4.9.0/node_modules/webpack/lib/NormalModule.js:580:19)
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.loader (/opt/xxxx/admin-complex/node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/index.js:31:27)
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in ./commended-tabbar.css
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Module build failed (from ../node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/cjs.js):
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  - options.url should be one of these:
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    boolean | object { filter? }
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Allows to enables/disables `url()`/`image-set()` functions handling.
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Read more at https://github.com/webpack-contrib/css-loader#url
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    Details:
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be a boolean.
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be an object:
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       object { filter? }
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at validate (/opt/xxxx/admin-complex/node_modules/.pnpm/schema-utils@3.1.1/node_modules/schema-utils/dist/validate.js:105:11)
2022-01-24 13:52:23.421  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.getOptions (/opt/xxxx/admin-complex/node_modules/.pnpm/webpack@5.67.0_webpack-cli@4.9.0/node_modules/webpack/lib/NormalModule.js:580:19)
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.loader (/opt/xxxxx/admin-complex/node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/index.js:31:27)
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in ./commended-textfields.css
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Module build failed (from ../node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/cjs.js):
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  - options.url should be one of these:
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    boolean | object { filter? }
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Allows to enables/disables `url()`/`image-set()` functions handling.
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Read more at https://github.com/webpack-contrib/css-loader#url
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    Details:
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be a boolean.
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be an object:
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       object { filter? }
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at validate (/opt/xxxx/admin-complex/node_modules/.pnpm/schema-utils@3.1.1/node_modules/schema-utils/dist/validate.js:105:11)
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.getOptions (/opt/xxxx/admin-complex/node_modules/.pnpm/webpack@5.67.0_webpack-cli@4.9.0/node_modules/webpack/lib/NormalModule.js:580:19)
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.loader (/opt/xxxx/admin-complex/node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/index.js:31:27)
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in ./mgacardboard.css
2022-01-24 13:52:23.422  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Module build failed (from ../node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/cjs.js):
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  - options.url should be one of these:
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    boolean | object { filter? }
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Allows to enables/disables `url()`/`image-set()` functions handling.
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Read more at https://github.com/webpack-contrib/css-loader#url
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    Details:
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be a boolean.
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be an object:
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       object { filter? }
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at validate (/opt/xxxx/admin-complex/node_modules/.pnpm/schema-utils@3.1.1/node_modules/schema-utils/dist/validate.js:105:11)
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.getOptions (/opt/xxxx/admin-complex/node_modules/.pnpm/webpack@5.67.0_webpack-cli@4.9.0/node_modules/webpack/lib/NormalModule.js:580:19)
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.loader (/opt/xxxx/admin-complex/node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/index.js:31:27)
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in ./mgacharts.css
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Module build failed (from ../node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/cjs.js):
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  - options.url should be one of these:
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    boolean | object { filter? }
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Allows to enables/disables `url()`/`image-set()` functions handling.
2022-01-24 13:52:23.423  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    -> Read more at https://github.com/webpack-contrib/css-loader#url
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    Details:
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be a boolean.
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     * options.url should be an object:
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       object { filter? }
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at validate (/opt/xxx/admin-complex/node_modules/.pnpm/schema-utils@3.1.1/node_modules/schema-utils/dist/validate.js:105:11)
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.getOptions (/opt/xxx/admin-complex/node_modules/.pnpm/webpack@5.67.0_webpack-cli@4.9.0/node_modules/webpack/lib/NormalModule.js:580:19)
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Object.loader (/opt/xxxx/admin-complex/node_modules/.pnpm/css-loader@6.5.1_webpack@5.67.0/node_modules/css-loader/dist/index.js:31:27)
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ERROR in Error: The loader "/opt/xxxx/admin-complex/node_modules/.pnpm/html-webpack  -plugin@4.5.1_webpack@5.67.0/node_modules/html-webpack-plugin/lib/loader.js!/o  pt/xxx/admin-complex/frontend/index.html" didn't return html.
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   - index.js:336 HtmlWebpackPlugin.evaluateCompilationResult
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     [admin-complex]/[html-webpack-plugin@4.5.1_webpack@5.67.0]/[html-webpack-plu    gin]/index.js:336:24
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   - index.js:243 
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     [admin-complex]/[html-webpack-plugin@4.5.1_webpack@5.67.0]/[html-webpack-plu    gin]/index.js:243:22
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   - runMicrotasks
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   - task_queues:96 processTicksAndRejections
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     node:internal/process/task_queues:96:5
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   - async Promise.all
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   - async Promise.all
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2022-01-24 13:52:23.424  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : webpack compiled with 7 errors
2022-01-24 13:52:23.474  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [build-status] 7 errors and 0 warnings were reported.
2022-01-24 13:52:23.475  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [build-status] : Failed to compile.

------------------ Frontend compilation failed. ------------------

2022-01-24 13:52:23.477  INFO 83662 --- [nPool-worker-19] c.v.b.devserver.AbstractDevServerRunner  : Started Webpack. Time: 5093ms
2022-01-24 13:52:23.492  INFO 83662 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : No issues found.


```

**Comment by Artur-** [comment]
You are using webpack 5 when you should be using webpack 4. Where does webpack 5 come from? Vaadin does not install that version

**Comment by magnusahlden** [comment]
**I have no clue** - but it's listed under devDependencies in the package.json file 
after removing package.json I managed to get the server up and running...
Thanks for getting that @Artur- !

**Comment by Artur-** [comment]
Good to hear. I will close this now as "Webpack Exited Prematurely" only means "There is some kind of problem running webpack" and we don't want to gather all unrelated problems into this same issue.

The original issue seems to have been about using `--ignore-scripts` which is also fixed by now
