### ISSUE TITLE
Server logging java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by byacobucci** [vaadin/platform#3825]
### Describe the bug

2023-02-22 07:10:46,147 ERROR [stderr] (default task-448) java.lang.IllegalArgumentException: The number of received values (5) is not equal to the number of arguments (6) in the method 'connectClient' declared in 'com.vaadin.flow.component.internal.JavaScriptBootstrapUI'
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.decodeArgs(PublishedServerEventHandlerRpcHandler.java:261)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:222)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:199)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:149)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:132)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:75)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1564)
2023-02-22 07:10:46,148 ERROR [stderr] (default task-448) 	at deployment.myApp.war//com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369)

### Expected-behavior

No Exception to be thrown

### Reproduction

I cannot reproduce although it happens a lot since upgrading from 23.2.16 to 23.3.

### System Info

Vaadin 23.3.6
Wildfly
Java 17

**Comment by Artur-** [comment]
This is caused by a mismatch of the code run in the browser and the version run on the server. Earlier versions sent 5 arguments from the browser, the new version sends 6

**Comment by byacobucci** [comment]
> This is caused by a mismatch of the code run in the browser and the version run on the server. Earlier versions sent 5 arguments from the browser, the new version sends 6

Thank  you for your quick reply. Is this something that can fixed? Or will the browser eventually load the new version into cache?

Ironically we went back to 23.2 and several times the reverse occurred (expecting 6 but got 5) but eventually stopped. Maybe the browser resynced.
