### ISSUE TITLE
Include hilla-dev-mode to platform

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#4946]
### Describe your motivation

Include `hilla-dev-mode` as a dependency to `vaadin-dev`. 
Remove `hilla-dev` from Hilla repository as it wouldn't be needed after that. 

### Additional context

Vaadin/Hilla 24.4.

**Comment by tltv** [comment]
Having `hilla-dev-mode` in `vaadin-dev` ends up some platform's dev mode integration tests to fail. Logs has just warnings that are not there when `hilla-dev-mode`  is not included.

Maybe it's better to leave `hilla-dev-mode` out of the `vaadin-dev` and just add it in hilla repository's `hilla` pom.xml. Or actually just rename `hilla-dev` to `hilla-dev-mode`. ([PR](https://github.com/vaadin/hilla/pull/1992))

If `hilla-dev-mode` has to go to the `vaadin-dev`, then these warnings need to be dealt some other way.

Server side warning:
```
[qtp888293905-94] WARN org.atmosphere.websocket.DefaultWebSocketProcessor - Failed invoking AtmosphereFramework.doCometSupport()
java.lang.NullPointerException: Cannot invoke "org.springframework.context.ApplicationContext.getAutowireCapableBeanFactory()" because the return value of "com.vaadin.hilla.ApplicationContextProvider.getApplicationContext()" is null
        at com.vaadin.hilla.devmode.devtools.DevToolsDatabase.initIfNeeded(DevToolsDatabase.java:48)
        at com.vaadin.hilla.devmode.devtools.DevToolsDatabase.handleConnect(DevToolsDatabase.java:29)
        at com.vaadin.base.devserver.DebugWindowConnection.handleConnect(DebugWindowConnection.java:222)
        at com.vaadin.base.devserver.DebugWindowConnection.onConnect(DebugWindowConnection.java:202)
        at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$3(PushHandler.java:599)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$4(PushHandler.java:598)
        at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:227)
        at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:595)
        at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
        at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103)
        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:213)
        at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:254)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onOpen(JakartaWebSocketFrameHandler.java:175)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$onOpen$6(WebSocketCoreSession.java:411)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1465)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1484)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onOpen(WebSocketCoreSession.java:411)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onOpen(WebSocketConnection.java:542)
        at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:451)
        at org.eclipse.jetty.server.HttpConnection.upgrade(HttpConnection.java:419)
        at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:450)
        at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:968)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:485)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

Browser console warnings:

```
[2024-01-26T13:12:30.082Z] [WARNING] http://localhost:8080/prod-mode/VAADIN/@fs/C:/Projects/Vaadin/platform/vaadin-platform-test/node_modules/@vaadin/bundles/vaadin.js?v=e4ab5536 176243:20 "Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information."
[2024-01-26T13:12:31.129Z] [WARNING] http://localhost:8080/prod-mode/VAADIN/@fs/C:/Projects/Vaadin/platform/vaadin-platform-test/node_modules/@vaadin/bundles/vaadin.js?v=e4ab5536 176243:20 "Overriding ReactiveElement.createProperty() is deprecated. The override will not be called with standard decorators See https://lit.dev/msg/no-override-create-property for more information."
[2024-01-26T13:12:31.129Z] [WARNING] http://localhost:8080/prod-mode/VAADIN/@fs/C:/Projects/Vaadin/platform/vaadin-platform-test/node_modules/@vaadin/bundles/vaadin.js?v=e4ab5536 176243:20 "Overriding ReactiveElement.getPropertyDescriptor() is deprecated. The override will not be called with standard decorators See https://lit.dev/msg/no-override-get-property-descriptor for more information."
[2024-01-26T13:12:32.652Z] [WARNING] http://localhost:8080/prod-mode/VAADIN/@fs/C:/Projects/Vaadin/platform/vaadin-platform-test/node_modules/@vaadin/bundles/vaadin.js?v=e4ab5536 176243:20 "Element vaadin-side-nav scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information."
[2024-01-26T13:12:32.654Z] [WARNING] http://localhost:8080/prod-mode/VAADIN/@fs/C:/Projects/Vaadin/platform/vaadin-platform-test/node_modules/@vaadin/bundles/vaadin.js?v=e4ab5536 176243:20 "Element vaadin-side-nav-item scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information."
[2024-01-26T13:12:32.836Z] [WARNING] http://localhost:8080/prod-mode/ - [DOM] Found 2 elements with non-unique id #button: (More info: https://goo.gl/9p2vKq) %o %o
```

Those above are extracted from local run, but simlar failures also in [CI validation here](https://teamcity.vaadin.com/buildConfiguration/VaadinPlatform_VaadinPlatformPrValidation/217636?buildTab=overview&expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false).

**Comment by tltv** [comment]
`hilla-dev-mode` depends on spring. It adds dependency to `spring-boot-autoconfigure` so that's probably why tests fails as non-spring ITs fails initializing `DevToolsDatabase`.

**Comment by mshabarov** [comment]
The problem is that when you want to exclude from production build the dependencies only needed for development mode, you usually exclude `vaadin-dev`.
If you don't add `hilla-dev` into `vaadin-dev`, you would need to exclude it explicitly in pom.xml, both `vaadin-dev` and `hilla-dev`.
This contradicts to unification goals.

**Comment by tltv** [comment]
So it's requirement to have `hilla-dev-mode` in `vaadin-dev` so that it's possible to exclude all dev mode dependencies with a single `vaadin-dev` exclusion for production build. However what complicates the case is that `hilla-dev-mode` can't be included to non-spring project. no solution yet. Suggestions welcome.

**Comment by tltv** [comment]
Making spring dependencies `provided` in `hilla-dev-mode` and catching and ignoring `NullPointerException` from `DevToolsDatabase` should help to make `hilla-dev-mode` to work in non-spring projects too.

**Comment by Artur-** [comment]
DevToolsDatabase can be deleted. It is integrated into copilot
