### ISSUE TITLE
13.0.0.beta2 causes java.lang.NoClassDefFoundError: com/googlecode/gentyref/GenericTypeReflector

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/platform#563]
Just tried to switch to 13.0.0.beta2 and getting the following warnings and errors with Maven build:

```
[WARNING] The POM for com.vaadin:flow-server:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:flow-push:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:flow-client:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:flow-html-components:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:flow-data:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:vaadin-lumo-theme:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:vaadin-material-theme:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.vaadin:flow-html-components-testbench:jar:1.4.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

and also

```
 Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$RouteServletContextListener]

java.lang.NoClassDefFoundError: com/googlecode/gentyref/GenericTypeReflector
	at com.vaadin.flow.router.ParameterDeserializer.isAnnotatedParameter(ParameterDeserializer.java:196) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.server.startup.RouteTarget.addTargetByType(RouteTarget.java:107) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.server.startup.RouteTarget.<init>(RouteTarget.java:80) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.internal.ConfigureRoutes.lambda$setRoute$0(ConfigureRoutes.java:134) ~[flow-server-1.4.0.jar:1.4.0]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[na:1.8.0_171]
	at com.vaadin.flow.router.internal.ConfigureRoutes.setRoute(ConfigureRoutes.java:133) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.addRouteToConfiguration(AbstractRouteRegistry.java:362) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$setRoute$83b15968$1(AbstractRouteRegistry.java:304) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configure(AbstractRouteRegistry.java:93) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.setRoute(AbstractRouteRegistry.java:303) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setRoute(ApplicationRouteRegistry.java:231) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.RouteConfiguration.setAnnotatedRoute(RouteConfiguration.java:225) ~[flow-server-1.4.0.jar:1.4.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_171]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$RouteServletContextListener.lambda$contextInitialized$785b83af$1(VaadinServletContextInitializer.java:99) ~[vaadin-spring-11.0.0.jar:na]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.update(AbstractRouteRegistry.java:104) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.RouteConfiguration.update(RouteConfiguration.java:203) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$RouteServletContextListener.contextInitialized(VaadinServletContextInitializer.java:97) ~[vaadin-spring-11.0.0.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.googlecode.gentyref.GenericTypeReflector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
	... 26 common frames omitted

2019-02-21 21:51:35.409 ERROR 28673 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$ErrorParameterServletContextListener]

java.lang.NoClassDefFoundError: com/googlecode/gentyref/GenericTypeReflector
	at com.vaadin.flow.internal.ReflectTools.getGenericInterfaceType(ReflectTools.java:580) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.addErrorTarget(AbstractRouteRegistry.java:387) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.lambda$setErrorNavigationTargets$2(ApplicationRouteRegistry.java:258) ~[flow-server-1.4.0.jar:1.4.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_171]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_171]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_171]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_171]
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setErrorNavigationTargets(ApplicationRouteRegistry.java:258) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$ErrorParameterServletContextListener.contextInitialized(VaadinServletContextInitializer.java:128) ~[vaadin-spring-11.0.0.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.googlecode.gentyref.GenericTypeReflector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
	... 24 common frames omitted
```

**Comment by heruan** [comment]
I'm on 13.0.0.beta2 and this doesn't happen to me. Did you try to clean your local Maven cache (`~/.m2/repository`)?

**Comment by martinisraelsen** [comment]
@heruan you were spot on, thanks!
