### ISSUE TITLE
New "flow-only" project fails to work with IntelliJ IDEA

### ISSUE THREAD

**Issue by jojule** [vaadin/platform#6828]
### Describe the bug

Downloading an empty project from start.vaadin.com, choosing 24.5 (pre), choosing "flow only", and opening the project in IntelliJ fails.

https://github.com/user-attachments/assets/76f8e3ef-88e8-41cc-8e2f-01dd383b1122

### Expected-behavior

Project should be compatible with IntelliJ IDEA

### Reproduction

See the screen recording above or test it yourself with attached project zip
[my-app.zip](https://github.com/user-attachments/files/17180811/my-app.zip)

### System Info

Darwin j16.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 21:29:10 PDT 2024; root:xnu-11215.1.10~5/RELEASE_ARM64_T6031 arm64

IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 24, 2024
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.vaadin.intellij-plugin (1.3.3)
  com.github.copilot (1.5.24.6840)
Kotlin: 242.23339.11-IJ

**Comment by jojule** [comment]
Also tested and reproduces with IDEA 2024.2.2 (Ultimate)

```
2024-09-30 17:19:50,682 [    261]   WARN - #c.i.u.x.Binding - No accessors for com.intellij.platform.experiment.ab.impl.experiment.ABExperimentGroupStorage. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-09-30 17:19:50,751 [    330]   WARN - c.i.o.u.r.overrides - Conflicting registry key definition for key kotlin.mpp.tests.force.gradle: it was defined by plugin org.jetbrains.kotlin but redefined by plugin org.jetbrains.kotlin. Consider adding overrides="true" for one of the plugins, see the documentation for com.intellij.openapi.util.registry.RegistryKeyBean.overrides for more details.
2024-09-30 17:19:50.801 idea[8093:26763616] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-30 17:19:50.801 idea[8093:26763616] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
2024-09-30 17:19:50,867 [    446]   WARN - #c.i.u.n.s.ConfirmingTrustManager - Received an empty list of custom trusted root certificates from the system. Check log above for possible errors, enable debug logging in category 'org.jetbrains.nativecerts' for more information
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=NOT_HEADLESS` must be used only for core services (service=org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService, plugin=org.jetbrains.kotlin)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=org.jetbrains.idea.maven.project.MavenProjectsManagerEx, plugin=org.jetbrains.idea.maven)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=org.jetbrains.idea.maven.navigator.MavenProjectsNavigator, plugin=org.jetbrains.idea.maven)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=org.jetbrains.idea.maven.tasks.MavenShortcutsManager, plugin=org.jetbrains.idea.maven)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=NOT_HEADLESS` must be used only for core services (service=com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.users.BackendUserManager, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.ports.CwmPortForwardingToolWindowManager, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,563 [   1142]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.users.BackendCWMUserFocusHost, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,564 [   1143]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.FollowMeManagerService, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,564 [   1143]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.BackendProjectViewSync, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,564 [   1143]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.BackendFollowMeEditorsHost, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,564 [   1143]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.BackendFollowMeDebuggerHost, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,564 [   1143]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.FollowMeLookupSynchronizer, plugin=com.jetbrains.codeWithMe)
2024-09-30 17:19:51,624 [   1203]   WARN - #c.i.u.x.Binding - No accessors for java.awt.Color. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-09-30 17:19:52,041 [   1620]   WARN - #c.i.u.x.Binding - No accessors for java.time.ZonedDateTime. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-09-30 17:19:52,115 [   1694]   WARN - #c.i.o.v.n.p.PersistentFSImpl - Can't find root[#573] in persistence
2024-09-30 17:19:52,403 [   1982]   WARN - #c.i.w.i.i.WorkspaceModelCacheSerializer - Workspace model cache was not serialized
com.intellij.platform.workspace.storage.metadata.exceptions.MissingTypeMetadataException: Metadata for the com.intellij.platform.workspace.jps.entities.LibraryEntity was not collected. Please run the generator for the class com.intellij.platform.workspace.jps.entities.LibraryEntity
	at com.intellij.platform.workspace.storage.metadata.MetadataStorage.getMetadataByTypeFqn(apiCode.kt:32)
	at com.intellij.platform.workspace.storage.metadata.resolver.TypeMetadataResolverImpl.resolveTypeMetadata(TypeMetadataResolver.kt:44)
	at com.intellij.platform.workspace.storage.impl.serialization.CacheMetadata$MutableCacheMetadata.add(CacheMetadata.kt:87)
	at com.intellij.platform.workspace.storage.impl.serialization.CacheMetadataKt.getCacheMetadata(CacheMetadata.kt:51)
	at com.intellij.platform.workspace.storage.impl.serialization.EntityStorageSerializerImpl.serializeCache(EntityStorageSerializerImpl.kt:107)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelCacheSerializer.saveCacheToFile$intellij_platform_ide_impl(WorkspaceModelCacheSerializer.kt:81)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelCacheImpl.doCacheSaving(WorkspaceModelCacheImpl.kt:121)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelCacheImpl.access$doCacheSaving(WorkspaceModelCacheImpl.kt:40)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelCacheImpl$2$1$1.invokeSuspend(WorkspaceModelCacheImpl.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
SLF4J: A SLF4J service provider failed to instantiate:
org.slf4j.spi.SLF4JServiceProvider: com.intellij.clouds.docker.devcontainers.cli.logging.SLF4JServiceProviderImpl not a subtype
SLF4J: A SLF4J service provider failed to instantiate:
org.slf4j.spi.SLF4JServiceProvider: org.slf4j.jul.JULServiceProvider not a subtype
[DefaultDispatcher-worker-24] INFO jetbrains.exodus.io.FileDataWriter - Uninterruptible file channel will be used
[DefaultDispatcher-worker-24] INFO jetbrains.exodus.env.EnvironmentImpl - Exodus environment created: /Users/phoenix/.config/github-copilot/iu/chat-sessions/2moTaDgqYO5LTlxABaAZOPOHpZj
2024-09-30 17:19:53,191 [   2770]   WARN - #org.intellij.plugins.markdown.ui.preview.jcef.impl.JcefBrowserPipeImpl - No subscribers for documentReady!
Attached data: 
2024-09-30 17:20:50,701 [  60280]   WARN - #c.i.u.x.Binding - No accessors for com.intellij.toolWindow.ToolWindowLayoutStorageManagerState. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
```

**Comment by Artur-** [comment]
Looks like a problem with your Maven cache

**Comment by ZheSun88** [comment]
downloaded the attached app, this issue is not happening with me. 
have you tried to reload the project or ask idea to download the resource?

**Comment by Artur-** [comment]
```
mvn com.github.s4u.plugins:pgpverify-maven-plugin:check
```

will find broken jars in your `~/.m2` folder

**Comment by jojule** [comment]
Something wrong in my setup. Deleting `~/.m2` did not help, but clearing all caches in IntelliJ did help.
