### ISSUE TITLE
Vaadin 24.6.0 doesn't compile the frontend, downgrade to 24.5.8 works as usually

### ISSUE THREAD

**Issue by jeannot-muller** [vaadin/platform#7139]
### Describe the bug

The flow compilation is working, but the frontend fails. I deleted the former build and caches.

```
------------------ Starting Frontend compilation. ------------------
2024-12-20T10:25:39.535+01:00  INFO 45587 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Running Vite to compile frontend resources. This may take a moment, please stand by...
10:25:39 [ForkJoinPool.commonPool-worker-1] INFO  c.v.b.d.AbstractDevServerRunner - Running Vite to compile frontend resources. This may take a moment, please stand by...
INFO  c.v.b.d.AbstractDevServerRunner - Running Vite to compile frontend resources. This may take a moment, please stand by...
2024-12-20T10:25:39.647+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ✘ [ERROR] Expected identifier but found "import"
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - ✘ [ERROR] Expected identifier but found "import"
INFO  c.v.b.d.DevServerOutputTracker - ✘ [ERROR] Expected identifier but found "import"
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - 
INFO  c.v.b.d.DevServerOutputTracker - 
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     (define name):1:0:
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     (define name):1:0:
INFO  c.v.b.d.DevServerOutputTracker -     (define name):1:0:
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       1 │ import.meta.dirname
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -       1 │ import.meta.dirname
INFO  c.v.b.d.DevServerOutputTracker -       1 │ import.meta.dirname
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :         ╵ ~~~~~~
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -         ╵ ~~~~~~
INFO  c.v.b.d.DevServerOutputTracker -         ╵ ~~~~~~
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - 
INFO  c.v.b.d.DevServerOutputTracker - 
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ✘ [ERROR] Expected identifier but found "import"
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - ✘ [ERROR] Expected identifier but found "import"
INFO  c.v.b.d.DevServerOutputTracker - ✘ [ERROR] Expected identifier but found "import"
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - 
INFO  c.v.b.d.DevServerOutputTracker - 
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     (define name):1:0:
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     (define name):1:0:
INFO  c.v.b.d.DevServerOutputTracker -     (define name):1:0:
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       1 │ import.meta.filename
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -       1 │ import.meta.filename
INFO  c.v.b.d.DevServerOutputTracker -       1 │ import.meta.filename
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :         ╵ ~~~~~~
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -         ╵ ~~~~~~
INFO  c.v.b.d.DevServerOutputTracker -         ╵ ~~~~~~
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - 
INFO  c.v.b.d.DevServerOutputTracker - 
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ✘ [ERROR] Expected identifier but found "import"
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - ✘ [ERROR] Expected identifier but found "import"
INFO  c.v.b.d.DevServerOutputTracker - ✘ [ERROR] Expected identifier but found "import"
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - 
INFO  c.v.b.d.DevServerOutputTracker - 
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     (define name):1:0:
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     (define name):1:0:
INFO  c.v.b.d.DevServerOutputTracker -     (define name):1:0:
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       1 │ import.meta.url
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -       1 │ import.meta.url
INFO  c.v.b.d.DevServerOutputTracker -       1 │ import.meta.url
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :         ╵ ~~~~~~
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -         ╵ ~~~~~~
INFO  c.v.b.d.DevServerOutputTracker -         ╵ ~~~~~~
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - 
INFO  c.v.b.d.DevServerOutputTracker - 
2024-12-20T10:25:39.648+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : failed to load config from /Users/jmu/java/myProject/vite.config.ts
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - failed to load config from /Users/jmu/java/myProject/vite.config.ts
INFO  c.v.b.d.DevServerOutputTracker - failed to load config from /Users/jmu/java/myProject/vite.config.ts
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : error when starting dev server:
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - error when starting dev server:
INFO  c.v.b.d.DevServerOutputTracker - error when starting dev server:
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Error: Build failed with 3 errors:
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - Error: Build failed with 3 errors:
INFO  c.v.b.d.DevServerOutputTracker - Error: Build failed with 3 errors:
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : (define name):1:0: ERROR: Expected identifier but found "import"
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - (define name):1:0: ERROR: Expected identifier but found "import"
INFO  c.v.b.d.DevServerOutputTracker - (define name):1:0: ERROR: Expected identifier but found "import"
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : (define name):1:0: ERROR: Expected identifier but found "import"
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - (define name):1:0: ERROR: Expected identifier but found "import"
INFO  c.v.b.d.DevServerOutputTracker - (define name):1:0: ERROR: Expected identifier but found "import"
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : (define name):1:0: ERROR: Expected identifier but found "import"
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker - (define name):1:0: ERROR: Expected identifier but found "import"
INFO  c.v.b.d.DevServerOutputTracker - (define name):1:0: ERROR: Expected identifier but found "import"
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at failureErrorWithLog (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1476:15)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at failureErrorWithLog (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1476:15)
INFO  c.v.b.d.DevServerOutputTracker -     at failureErrorWithLog (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1476:15)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at /Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:945:25
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at /Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:945:25
INFO  c.v.b.d.DevServerOutputTracker -     at /Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:945:25
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at runOnEndCallbacks (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1316:45)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at runOnEndCallbacks (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1316:45)
INFO  c.v.b.d.DevServerOutputTracker -     at runOnEndCallbacks (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1316:45)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at buildResponseToResult (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:943:7)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at buildResponseToResult (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:943:7)
INFO  c.v.b.d.DevServerOutputTracker -     at buildResponseToResult (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:943:7)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at /Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:970:16
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at /Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:970:16
INFO  c.v.b.d.DevServerOutputTracker -     at /Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:970:16
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at responseCallbacks.<computed> (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:622:9)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at responseCallbacks.<computed> (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:622:9)
INFO  c.v.b.d.DevServerOutputTracker -     at responseCallbacks.<computed> (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:622:9)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at handleIncomingPacket (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:677:12)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at handleIncomingPacket (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:677:12)
INFO  c.v.b.d.DevServerOutputTracker -     at handleIncomingPacket (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:677:12)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Socket.readFromStdout (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:600:7)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at Socket.readFromStdout (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:600:7)
INFO  c.v.b.d.DevServerOutputTracker -     at Socket.readFromStdout (/Users/jmu/java/myProject/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:600:7)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Socket.emit (node:events:514:28)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at Socket.emit (node:events:514:28)
INFO  c.v.b.d.DevServerOutputTracker -     at Socket.emit (node:events:514:28)
2024-12-20T10:25:39.649+01:00  INFO 45587 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at addChunk (node:internal/streams/readable:545:12)
10:25:39 [dev-server-output] INFO  c.v.b.d.DevServerOutputTracker -     at addChunk (node:internal/streams/readable:545:12)
INFO  c.v.b.d.DevServerOutputTracker -     at addChunk (node:internal/streams/readable:545:12)

------------------ Frontend compilation failed. ------------------
```

### Expected-behavior

Working compilation.

### Reproduction

Happens on multiple computers

### System Info

macOS 15.2, Vaadin 24.6.0, Chrome 131.0.6778.205 (Official Build) (arm64)

**Comment by Artur-** [comment]
This is a problem in a recently released esbuild: https://github.com/evanw/esbuild/issues/4010

As long as you have the existing `package-lock.json` in the project, you should not experience it

**Comment by jeannot-muller** [comment]
ah, great ... thank you. I was wondering, as I had the perception that it did still work yesterday.

**Comment by pepijnve** [comment]
I was able to work around the problem using an override in package.json that forces esbuild 0.24.0 to be used. See https://github.com/vitejs/vite/issues/19018

**Comment by jeannot-muller** [comment]
yes, I can confirm that this is working. A bit of a dirty workaround but it doesn the job! Thank you all!
