### ISSUE TITLE
Vaadin 14 spring Starter, war packaged upload in tomcat manually

### ISSUE THREAD

**Issue by jeemsk** [vaadin/platform#826]
Hi, im usin de vaadin 14 starter version of spring.

but when i want to deploy in war version with this added configurations

<packaging>war</packaging>

<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-tomcat</artifactId>
<scope>provided</scope>
</dependency>

The log show me this error.

2019-09-02 13:04:40.402  INFO 1 --- [io-8080-exec-87] com.sisint.unopetrol.spring.Application  : No active profile set, falling back to default profiles: default
2019-09-02 13:04:43.087  INFO 1 --- [io-8080-exec-87] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2562 ms
2019-09-02 13:04:45.716  INFO 1 --- [io-8080-exec-87] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-09-02 13:04:46.636  INFO 1 --- [io-8080-exec-87] com.sisint.unopetrol.spring.Application  : Started Application in 7.654 seconds (JVM running for 136938.728)
2019-09-02 13:04:46.853  INFO 1 --- [io-8080-exec-87] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in C:\Informacion\D\Sisintegrados\Examples\wauweb folder.
2019-09-02 13:04:46.943  INFO 1 --- [io-8080-exec-87] dev-updater                              : Scanning classes to find frontend configurations and dependencies...
2019-09-02 13:04:50.514  INFO 1 --- [io-8080-exec-87] dev-updater                              : Visited 658 classes. Took 3567 ms.
2019-09-02 13:04:50.537  INFO 1 --- [io-8080-exec-87] dev-updater                              : Added "name": "no-name" line.
2019-09-02 13:04:50.542  INFO 1 --- [io-8080-exec-87] dev-updater                              : Added "license": "UNLICENSED" line.
2019-09-02 13:04:50.542  INFO 1 --- [io-8080-exec-87] dev-updater                              : Added "@polymer/polymer": "3.2.0" line.
2019-09-02 13:04:50.542  INFO 1 --- [io-8080-exec-87] dev-updater                              : Added "@webcomponents/webcomponentsjs": "^2.2.10" line.
02-Sep-2019 13:04:50.544 SEVERE [http-nio-8080-exec-87] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/usr/local/tomcat/webapps/wauweb##2.0.war]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:493)
                at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1642)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:567)
                at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:289)
                at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
                at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
                at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1590)
                at org.apache.catalina.manager.HTMLManagerServlet.upload(HTMLManagerServlet.java:294)
                at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:212)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:643)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:835)
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/wauweb##2.0]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                ... 42 more
        Caused by: java.lang.IllegalArgumentException: 'other' is different type of Path
                at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:429)
                at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
                at com.vaadin.flow.server.frontend.NodeUpdater.updateMainDefaultDependencies(NodeUpdater.java:215)
                at com.vaadin.flow.server.frontend.TaskCreatePackageJson.execute(TaskCreatePackageJson.java:50)
                at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:368)
                at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:248)
                at com.vaadin.flow.server.startup.DevModeInitializer.onStartup(DevModeInitializer.java:164)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                ... 43 more
02-Sep-2019 13:04:50.564 INFO [http-nio-8080-exec-87] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/wauweb##2.0.war] has finished in [16,492] ms

**Comment by ZheSun88** [comment]
Hi @jeemsk ,

Thanks for using Vaadin 14. `vaadin-spring`(https://github.com/vaadin/spring) is one of our supported add-on components. 

With this particular question, I would suggest you:

**If you think this is a bug**, please create a ticket for `vaadin-spring` repo (https://github.com/vaadin/spring/issues), also, please, tell us the steps to reproduce this error.

**If you want to look for some solutions for your question**, you can also visit our forum (https://vaadin.com/forum), there are quite many useful info which might be helpful to you. 

Thank you.

**Comment by jeemsk** [comment]
ok, Thaks, i will put this in thath thread.


Thanks a lot
